### ISSUE TITLE
component ส่วนที่ 4 การผสมพันธ์ุ ประสิทธิภาพการผลิต และการรักษาโรค

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#11]
![image](https://user-images.githubusercontent.com/37680321/41141234-6b858532-6b1b-11e8-88b0-193eab4014b2.png)
![image](https://user-images.githubusercontent.com/37680321/41141245-7af3b55c-6b1b-11e8-9909-efe4a3b5f4ec.png)
![image](https://user-images.githubusercontent.com/37680321/41141254-8460b0fe-6b1b-11e8-8c66-a9f83ecab05e.png)
![image](https://user-images.githubusercontent.com/37680321/41141265-90ed1aec-6b1b-11e8-9b3d-481320f80996.png)

**Comment by ford19982541** [comment]
4.7 con't not edit and save
