### ISSUE TITLE
component ส่วนที่ 5 ข้อมูลแหล่งเงินทุนที่ใช้ในการเลี้ยงโคเนื้อ

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#12]
![image](https://user-images.githubusercontent.com/37680321/41141306-bcf71188-6b1b-11e8-9f1d-48ebffa60bfc.png)
![image](https://user-images.githubusercontent.com/37680321/41141312-c3fde948-6b1b-11e8-8717-ee68a3a076e3.png)

**Comment by MyMost24** [comment]
5.2 และ 5.3 ยังทำไม่เสร็จครับ

**Comment by MyMost24** [comment]
ทำ SumBudget ข้อ 5.3

**Comment by MyMost24** [comment]
hard code เงินกู้จากธนาคารพาณิชย์ ใน 5.2
