### ISSUE TITLE
component ส่วนที่ 7 การได้รับบริการ การส่งเสริมและสนับสนุนจากหน่วยงานต่างๆ

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#14]
![image](https://user-images.githubusercontent.com/37680321/41141448-2d2a1626-6b1c-11e8-9ef8-bbf7b2bae7bd.png)
![image](https://user-images.githubusercontent.com/37680321/41141458-35b391c8-6b1c-11e8-9b64-02dd7104bd5f.png)

**Comment by ford19982541** [comment]
เลือก api/choices ไม่ถูก 
มี เคย และ ไม่เคย หลายตัวยังไม่มันใจว่าใช้รวมกันได้รึป่าว
