### ISSUE TITLE
API สำหรับเเสดง farm-owner

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#19]

**Comment by porrametict** [comment]
![image](https://user-images.githubusercontent.com/37680321/41187248-6f93981c-6bcf-11e8-9c81-0d17437273dd.png)
-------------------------------------------------------------------------------------------------------------------
 สิ่งที่ยังไม่สมบูรณ์

- ยังไม่สามารถค้นหาจาก จังหวัด อำเภอ เเละ ตำบลได้ 
- ยังไม่สามารถค้นหาจาก ประเภทโคที่เลี่ยงได้ 
- ยังไม่สามารถ export ได้
- ยังไม่กล้าลบ เพราะคิดว่าน่าเป็นข้อมูลจริง ที่สำคัญ 
------------------------------------------------------ความต้องการ------------------------------------------------
?? รบกวนขอทราบ  type ของ select choices ประเภทโคที่เลี้ยง  เเละสิ่งที่ต้องใส่ลงไปในฟอร์ม(ส่วนตัวความว่าน่าจะโยนลงไปทั้งหมด)
?? สิ่งที่ต้องใส่ลงไปในฟอร์มที่เพื่อที่จะค้นหา โดย จังหวัด อำเภอ ไอดี (ไม่เเน่ใจว่าใช้ไอดีอย่างเดี๋ยวหรือไม่)


ขอบคุณล่วงหน้าครับ

**Comment by pchaow** [comment]
ข้อมูลการส่งจังหวัด อำเภอ ตำบล
ให้ ส่งเป็นตัวเลข ของรหัส จังหวัด อำเภอ ตำบล
ไว้ในตัวแปร form 
โดยใช้ชื่อว่า province amphur และ ตำบลตามลำดับ

**Comment by pchaow** [comment]
ส่วน ประเภทโคที่เลี้ยง ให้ส่งไปในตัวแปร
breeding ใน form โดยส่งเป็น id (ตัวเลขของตัวเลือก)

**Comment by porrametict** [comment]
ยังไม่สามารถค้นหา จาd จังหวัด อำเภอ ตำบลได้ 
ตัวอย่างข้อมูลที่ส่ง
![image](https://user-images.githubusercontent.com/37680321/41391859-3a390ffc-6fc7-11e8-8de1-3172b0aec1ee.png)
ไม่ข้อผิดพลาดใดๆ เเสดงใน console เเละ network ข้อมูลที่ตีกลับมา เมื่อเช็ค network เป็นข้อมูลที่ไม่มีการเปลี่ยนเเปลง

**Comment by porrametict** [comment]
sever http://mct.ict.up.ac.th:10007/ ไม่สามารถค้นหาจาก จังหวัด อำเภอ ตำบล ได้

**Comment by porrametict** [comment]
sever 10007 ไม่สามารถค้นหาจาก จังหวัด อำเภอ ตำบล ได้
