### ISSUE TITLE
API สำหรับเเก้ไข farm-owner เเต่ละคน เเละ ลบเกษตรกร

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#20]

**Comment by porrametict** [comment]
ไม่สามารถ ลบ เเก้ไขได้  server ไม่อนุญาติครับ 
![image](https://user-images.githubusercontent.com/37680321/41280380-0029507a-6e59-11e8-896e-255039f071d6.png)

**Comment by pchaow** [comment]
fix 
รอสำหรับ Login 
ย้ายไป milestone 2

**Comment by porrametict** [comment]
เหมือนว่า server 10007 หลักจะไม่ยอมให้เเก้ไขนะครับ
![image](https://user-images.githubusercontent.com/37680321/41509753-0870427e-7283-11e8-9d6e-1368bfd684dd.png)
![image](https://user-images.githubusercontent.com/37680321/41509758-101f5168-7283-11e8-9847-600ed56f385a.png)

**Comment by porrametict** [comment]
server http://mct.ict.up.ac.th:10007/ ไม่สามารถเเก้ไขข้อมูลได้ error 500
