### ISSUE TITLE
เเก้ ระบบเเจ้งเตือน error 

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#24]
มันเเจ้งเตือนเเค่ครั้งเเรกเท่านั้น หากมีการผิดพลาดรอบที่สองจะไม่มีการเเจ้งเตือน

**Comment by pchaow** [comment]
![default](https://user-images.githubusercontent.com/5770600/42194744-abd16f24-7e9f-11e8-8fc0-e9b75b035ffd.png)
แก้ไขโดยใส่ setTimeout ใน vuex
