### ISSUE TITLE
[CattleAdmin] เข้าสู่ระบบไม่ได้

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#25]
administrator@app.com
password

**Comment by pchaow** [comment]
error ยังไง

**Comment by porrametict** [comment]
![image](https://user-images.githubusercontent.com/37680321/42173745-437c40e8-7e4a-11e8-9f8e-2132fe2004a7.png)
ตามนี้ครับ

**Comment by pchaow** [comment]
สาเหตุเกิดจากการ configuration ที่ล๊อคไว้สำหรับ dev server แนวทางแก้ไขคือ ไปเซ็ต configuration สำหรับ dev / prod ในการ Login ให้เรียบร้อย
![default](https://user-images.githubusercontent.com/5770600/42194195-000867e4-7e9d-11e8-8e2c-5fcaa9c26ed5.png)
