### ISSUE TITLE
เเก้ ไม่สามารถเพิ่ม user ไม่ได้ 'name' of undefined'

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#37]
SQLSTATE[HY000]: General error: 1364 Field 'username' doesn't have a default value (SQL: insert into `users` (`user_province`, `user_amphur`, `user_district`, `name`, `email`, `password`, `updated_at`, `created_at`) values (, , , cat, cat@cat.cat, $2y$10$yKMkfj/cl1RrajjC4oKIc..Gx7jUMYOrVvLhS9Hq/s2ekMUBPyNx6, 2018-07-01 00:06:46, 2018-07-01 00:06:46))

![image](https://user-images.githubusercontent.com/37680321/42129936-969f1a28-7cfd-11e8-921a-daa5d1524c3a.png)

**Comment by pchaow** [comment]
แก้ไปยังนิ ปิดละนะ
