### ISSUE TITLE
ไม่สามารถ เเก้ไข farm-owner ได้(ในบางครั้ง)

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#38]
![image](https://user-images.githubusercontent.com/37680321/42132201-d47c53d4-7d3d-11e8-84b0-efc600be5e20.png)

**Comment by porrametict** [comment]
ข้อมูลจริงๆ ถูกเเก้ไขเเล้ว เเต่ เหมือนจะ ส่งกลับมาไม่ทันหรือยังไงครับผมไม่เน่ใจ
![image](https://user-images.githubusercontent.com/37680321/42174470-ad6a4322-7e4c-11e8-8759-45efde61f13e.png)
 
![image](https://user-images.githubusercontent.com/37680321/42174479-b2f8de3e-7e4c-11e8-960a-206e8b90abcb.png)

**Comment by pchaow** [comment]
อาการนี้คือมันประมวลผลไม่ทันอ่ะ timeout error ต้องหาวิธีที่ทำให้ประมวลผลเร็วขึ้น

**Comment by pchaow** [comment]
ต้อง config server ให้ รองรับระยะเวลานานกว่านี้
