### ISSUE TITLE
ติดต่อserver ไม่ได้ครับ

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#39]
10007 ครับ
![image](https://user-images.githubusercontent.com/37680321/42193498-f0db4bbe-7e98-11e8-8998-3d0b59246fc5.png)

**Comment by porrametict** [comment]
10002 ครับ
![image](https://user-images.githubusercontent.com/37680321/42193582-6ebb3738-7e99-11e8-91bb-968e40d87477.png)

**Comment by pchaow** [comment]
dev server ไฟดับป่าว

**Comment by porrametict** [comment]
อันนี้ไม่ทราบครับ
