### ISSUE TITLE
[CattleServer] sever ไม่ส่งuserมาให้ 

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#42]
ได้รับtoken เเต่ ไม่มีuserมา หลังจากส่ง token ไปเเล้ว
![image](https://user-images.githubusercontent.com/37680321/42252259-00125c08-7f66-11e8-9009-42cf8e3f19d5.png)

**Comment by pchaow** [comment]
ลองดูอีกรอบหน่อย

**Comment by porrametict** [comment]
ได้เเล้วครับ
