### ISSUE TITLE
ฟอร์มเพิ่มและแก้ไขผู้ใช้

### ISSUE THREAD

**Issue by pchaow** [SEUP/CattleAdmin#5]
ประกอบไปด้วย
- ชื่อ-นามสกุล
- Username
- E-mail
- password
- verifypassword
- ตัวเลือกสิทธิ์

**Comment by pchaow** [comment]
แก้ไขนะครับ ชื่อ นามสกุลแยก ช่องกันนะครับเป็น
firstname และ lastname

**Comment by ford19982541** [comment]
ส่ง id ของ user ไปให้แล้ว เอา data ออกมาโชว์

**Comment by pchaow** [comment]
เตรียมสำหรับการแสดง Error และ notification

**Comment by ford19982541** [comment]
Page add user
Sever error 500 
Not post to sever

**Comment by ford19982541** [comment]
![image](https://user-images.githubusercontent.com/33016279/41403008-fb878910-6fed-11e8-9ea1-d2e4c1dbfa8b.png)
