### ISSUE TITLE
หน้าเเสดงบันทึกข้อมูลเกษตรกรใหม่ 

### ISSUE THREAD

**Issue by porrametict** [SEUP/CattleAdmin#7]
![image](https://user-images.githubusercontent.com/37680321/41140788-97c8bdbe-6b19-11e8-9dd4-b8acb35e9445.png)

**Comment by ford19982541** [comment]
https://codepen.io/developerplus/pen/mBbjBq  /////top

**Comment by ford19982541** [comment]
405 Method Not Allowed 
Method is POST
